### ISSUE TITLE
Why you have used 2 Recycler view?

### ISSUE THREAD

**Issue by SkyTreasure** [SaravanakumarB/Web_view_in_RecyclerView#1]
Hi,

Any specific reason why you have used 2 recycler views one inside the other?

**Comment by SaravanakumarB** [comment]
i have used two recycler view to achieve, First recycler view (vertical) is for displaying video vertically (list of videos) . Second recycler view (horizontal) is for displaying multiple video in the element (item or position) of First Recycler view. There are other solution too, recycler view with view pager. I faced few problem in viewpager. So I have used horizontal recycler view within vertical recycler view to achieve it. These is different approach.

**Comment by SkyTreasure** [comment]
ok ok cool thank you :)
